### ISSUE TITLE
Package cannot be used because it tries to build stuff

### ISSUE THREAD

**Issue by GrimMaple** [BindBC/bindbc-imgui#3]
Because this package is setup in a way that tries to build dependenceis as a dub build step, this package is actually unusable.
Not only it wants to build something, it also requires Visual Studio 17 2022 to be installed

**Comment by ichordev** [comment]
The latest tagged release from this repository is a legacy mirror of: https://github.com/Inochi2D/i2d-imgui This is due to me taking ownership of the package name to make my own bindings with (see latest commit [here](https://github.com/ichordev/bindbc-imgui) for WIP new bindings that will link with object files built by any compiler)
If you want to submit an issue about the old library, this is not the place for it unfortunately.
